name: Gradle build

on:
  workflow_dispatch:
  push:
    branches: ["main", "dev/*"]
  pull_request:
    branches: ["main", "dev/*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK 21
        uses: actions/setup-java@v4.0.0
        with:
          java-version: "21"
          distribution: "temurin"
          check-latest: true
          cache: gradle
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3.1.0
        with:
          arguments: shadowJar
      - name: Upload jarfiles
        uses: actions/upload-artifact@v4.3.1
        with:
          path: plugin/build/libs/*.jar
